test: &test
  steps:
    - checkout
    - run:
        name: Download conda
        command: |
          curl -Ls -o $HOME/miniconda.sh https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh
    - run:
        name: Install conda
        command: bash $HOME/miniconda.sh -b -p $HOME/miniconda
    - run:
        name: Create conda environment
        command: |
          $HOME/miniconda/bin/conda create -q -n slumba -y -c conda-forge python="$PYTHON" numba nomkl
    - run:
        name: Activate environment
        command: |
          echo 'export PATH=$HOME/miniconda/bin:$PATH' >> $BASH_ENV
          echo 'source activate slumba' >> $BASH_ENV
    - run:
        name: Install dependencies
        command: |
          pip install -r requirements.txt
    - run:
        name: Install dev dependencies
        command: |
          pip install -r requirements_dev.txt
    - run:
        name: Install package
        command: |
          python setup.py develop
    - run:
        name: Make test reports directory
        command: mkdir -p /tmp/test-reports/pytest
    - run:
        name: Execute Pytest
        command: |
          pytest -ra --junitxml=/tmp/test-reports/pytest/junit.xml
    - store_test_results:
        path: /tmp/test-reports
    - store_artifacts:
        path: /tmp/test-reports

jobs:
  python36_test:
    docker:
      - image: circleci/python:3.6
    <<: *test
    environment:
      PYTHON: 3.6

workflows:
  version: 2
  test:
    jobs:
      - python36_test
